version: "3.9"

services:
  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/00-init.sql:ro

  redis:
    image: redis:7
    container_name: redis

  python-api:
    build: ./python-api
    container_name: python-api
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  celery-worker:
    build: ./python-api
    container_name: celery-worker
    depends_on:
      - db
      - redis
    command: ["celery", "-A", "app.tasks.celery_app", "worker", "--loglevel=info"]

  rust-api:
    build: ./rust-api
    container_name: rust-api
    depends_on:
      - python-api
    ports:
      - "8080:8080"
volumes:
  db-data: